### ISSUE TITLE
not removing owned servers from checking list

### ISSUE THREAD

**Issue by mr-459** [noptrix/sshprank#12]
hi
this script is not removing owned servers from checking list
example:
2000 ip is entered
100 passwords are entered
ip 123.123.123.123 is cracked and that is in owned.txt
then app again checks next password in 123.123.123.123
please fix this

**Comment by k79e** [comment]
I have this problem too. And -e is not work!

**Comment by noptrix** [comment]
@mr-459 @k79e ok thanks for reporting this. will be fixed. yes `-e` has a placeholder in code. i will implement it.

**Comment by noptrix** [comment]
should be done. you can use `-e` and `-E` also
