### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by VoipSip** [noptrix/sshprank#13]
the script not checks next password in 123.123.123.123
please fix this to make all the password and checking one by one after finish the first password take the next one and try to crack

**Comment by VoipSip** [comment]
-p                    - single password (default: root)
  -P <file>             - list of passwords

**Comment by noptrix** [comment]
:watermelon:

**Comment by VoipSip** [comment]
it working well with -C but i have more Feature i hope to do this to be not blocked from cracking added Tor  Proxy

**Comment by noptrix** [comment]
@VoipSip dude, i don't know what you want to be honest. show me errors or anything and try to describe the issue better.
