### ISSUE TITLE
issue with masscan

### ISSUE THREAD

**Issue by donesmarcos30** [noptrix/sshprank#14]
Hello sir,

I'm facing a problem when I try to use masscan.

scanning sshds[-] unknown masscan error occured: str('masscan program was not found in path. PATH is : /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin')

any idea about how to fix this?

I installed last version of masscan and python is 3.8

Thanks a lot!

**Comment by noptrix** [comment]
@donesmarcos30 you need to install the tool `masscan` and the python lib `python-masscan`. feel free to re-open this issue if persists
