### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by TormentedSoul666** [noptrix/sshprank#18]
I've tried this "tool" against some SSH servers i administrate to test if fail2ban triggers correctly and even when putting very simple and specific commands like "wget https://www.google.com" into the file put under -C it doesn't run this command, even tho it detects the credential I've put into the combo under -c (multiple times, the -e switch is not working at all).
Some other tests in red teaming also only delivered (multiple times the same) false positives.

What's the point of putting a tool at prod, which is a) completely unreliable, b) terribly hungry concerning resources and c) not working properly at all?

I mean it's cool and shit to link it on your website (sshtrix was about the same level of quality) but that's all and you fuck up your reputation and others peoples (working) time.

**Comment by TormentedSoul666** [comment]
At least beta test your stuff.

**Comment by noptrix** [comment]
@TormentedSoul666 will be fixed in upcoming version. chill a bit
