### ISSUE TITLE
[Feature Request] Remove addresses that sshprank can't connect to.

### ISSUE THREAD

**Issue by BroHowAreYou** [noptrix/sshprank#3]
SSHPrank wastes a lot of time on brute force runs if one or more of the IP addresses in the list fails to connect. It iterates through all username/password combinations on those addresses even if it can't connect. 

It would be great if there was an optional flag to only run brute forcing on IP addresses that are actually online, saving the time wasted on offline servers.

**Comment by BroHowAreYou** [comment]
the -r option has this issue too.

**Comment by noptrix** [comment]
@BroHowAreYou thanks a lot dude. i never noticed that :) i will work on this and let the progress know.

**Comment by noptrix** [comment]
@BroHowAreYou feel free to reopen if i broke something or something is fucked due to my last changes.

**Comment by mr-459** [comment]
> 
> 
> @BroHowAreYou feel free to reopen if i broke something or something is fucked due to my last changes.

now i most use options to remove invalid hosts?
or its on by default?
