### ISSUE TITLE
WHAT'S WRONG bro

### ISSUE THREAD

**Issue by Stakingsoup** [noptrix/sshprank#7]
![Screenshot_2020-06-08-14-40-01-51](https://user-images.githubusercontent.com/58569784/84004782-52596400-a996-11ea-945b-84e27cb4adaa.jpg)
Whats Wrong Bro???

My Combos Format Like That..
root:admin
admin:admin
telnet:telnet
ubnt:ubnt
user:user
support:support
0000:0000
1111:1111
admin:password
admin:1234567890
osmc:osmc
pi:raspberry
operator:operator
pi:1234
root:pi
user:123456
service:service
root:linux
root:password

**Comment by noptrix** [comment]
delete empty lines (first and last line in your file) and try again. feel free to re-open if still not working

**Comment by Stakingsoup** [comment]
Okay bro thanks ,solved

Pada tanggal Sen, 8 Jun 2020 3.43 PM, noptrix <notifications@github.com>
menulis:
