### ISSUE TITLE
errore at run

### ISSUE THREAD

**Issue by mr-459** [noptrix/sshprank#8]
hy i got this errore at run
i have installed all req...

	 root@server$ python3 sshprank.py
  	File "sshprank.py", line 172
 	   iprefix = f'{BOLD}{BLUE}[+] {NORM}'
	                                      ^
	SyntaxError: invalid syntax

runing on wsl

**Comment by sepehrdaddev** [comment]
@mr-459 what version of wsl are you running ?

**Comment by mr-459** [comment]
> 
> 
> @mr-459 what version of wsl are you running ?

wsl 1 - ubuntu 18.04

**Comment by mr-459** [comment]
windows server 2019

**Comment by sepehrdaddev** [comment]
@mr-459, could you please use wsl 2.0 and see what the result would be ?

**Comment by mr-459** [comment]
> 
> 
> @mr-459, could you please use wsl 2.0 and see what the result would be ?

hi
my server dont support wsl2
the windows build is old



and 1 quasstion

can i use this script with python on windows?

**Comment by sepehrdaddev** [comment]
@mr-459, try it and if it didn't work paste the error message and we will try to fix it

**Comment by mr-459** [comment]
> 
> 
> @mr-459, try it and if it didn't work paste the error message and we will try to fix it

working with windows
its great
