### ISSUE TITLE
high memory usage

### ISSUE THREAD

**Issue by mr-459** [noptrix/sshprank#9]
hi
i want to brute force 370 000 ips with 10 000 pw
but script use 14gb memory for that
its very much
please optimize memory usage

**Comment by noptrix** [comment]
@mr-459 ok thx. will optimize it.

**Comment by mr-459** [comment]
> 
> 
> @mr-459 ok thx. will optimize it.

my suggestion to optimize:
create servers.txt file and dont ue momry as that
create credential.txt file and dont use memory as that
then in status.ini file you write witch pw on witch server has tested
for example:
pw 1 until sevrer 5247 tested
or 
pw 843 on tested until server 98023


script save status every mineate
and now memory usage is only for connection
and it get's used about 300mb in 1000 thered

**Comment by noptrix** [comment]
@mr-459 sorry for the delay :) should be fixed now...
